# Generated by Django 6.0 on 2026-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('image', models.ImageField(upload_to='services/', verbose_name='صورة الخدمة')),
            ],
        ),
    ]
