# Generated by Django 6.0 on 2026-01-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalZone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='اسم المستشفى / العيادة')),
                ('device_type', models.CharField(max_length=200, verbose_name='نوع الجهاز الطبي')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('pending', 'قيد الإصلاح'), ('completed', 'تمت الصيانه')], default='new', max_length=20, verbose_name='حالة الطلب')),
            ],
        ),
    ]
